os: linux
dist: bionic
language: java

before_install:
  - echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc
  - mkdir -p $HOME/.downloads
  - git submodule update --init --recursive
