os: linux
dist: bionic
language: java
cache:
  directories:
    - $HOME/.m2
    - $HOME/.downloads

before_install:
  - echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc
  - mkdir -p $HOME/.downloads

jobs:
  fast_finish: true
  include:
    # checkstyle
    - jdk: openjdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn clean checkstyle:check"
        - LANG=en_US.utf8

    - jdk: openjdk8
      env:
        - DESC="openjdk8 unit tests"
        - CMD="mvn clean test -Dcheckstyle.skip=true"
        - LANG=en_US.utf8

script: echo ${CMD}; ${CMD}
