os: linux
dist: bionic
language: java
jdk:
  - openjdk9

before_install:
  - echo 'MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=warn"' >~/.mavenrc
  - git submodule update --init --recursive

install: true

script:
  - cd ./flow
  - echo $PWD
  - mvn clean install
  - cd ..
  - mvn clean test -B